##
# This file is part of the WikiTagBundle package.
#
# (c) IRI <http://www.iri.centrepompidou.fr/>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

IRI\Bundle\WikiTagBundle\Entity\Category:
  type: entity
  repositoryClass: IRI\Bundle\WikiTagBundle\Entity\CategoryRepository
  table: wikitag_category
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    label:
      type: string
      length: '512'
  lifecycleCallbacks: {  }
