##
# This file is part of the WikiTagBundle package.
#
# (c) IRI <http://www.iri.centrepompidou.fr/>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

IRI\Bundle\WikiTagBundle\Entity\Tag:
  type: entity
  repositoryClass: IRI\Bundle\WikiTagBundle\Entity\TagRepository
  table: wikitag_tag
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    label:
      type: string
      length: '1024'
    normalizedLabel:
      type: string
      length: '1024'
      column: normalized_label
    originalLabel:
      type: string
      length: '1024'
      column: original_label
    alternativeLabel:
      type: string
      length: '1024'
      column: alternative_label
      nullable: true
    alias:
      type: string
      length: '1024'
      nullable: true
    wikipediaUrl:
      type: string
      length: '2048'
      column: wikipedia_url
      nullable: true
    alternativeWikipediaUrl:
      type: string
      length: '2048'
      column: wikipedia_alternative_url
      nullable: true
    wikipediaPageId:
      type: bigint
      column: wikipedia_pageid
      nullable: true
    alternativeWikipediaPageId:
      type: bigint
      column: alternative_wikipedia_pageid
      nullable: true
    urlStatus:
      type: smallint
      column: url_status
      nullable: true
    dbpediaUri:
      type: string
      length: '2048'
      column: dbpedia_uri
      nullable: true
    popularity:
      type: integer
    createdAt:
      type: datetime
      column: created_at
      nullable: false
      
  manyToOne:
    category:
      targetEntity: Category
  oneToMany:
    documents:
      targetEntity: DocumentTag
      mappedBy: tag
  lifecycleCallbacks: {  }
