##
# This file is part of the WikiTagBundle package.
#
# (c) IRI <http://www.iri.centrepompidou.fr/>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

wikitag_home:
    pattern:  /
    defaults: { _controller: WikiTagBundle:WikiTag:index }
wikitag_alltags:
    pattern:  /alltags
    defaults: { _controller: WikiTagBundle:WikiTag:allTags }
wikitag_doctags:
    pattern:  /doctags
    defaults: { _controller: WikiTagBundle:WikiTag:documentTags }
wikitag_tag_up_down:
    pattern:  /wttud
    defaults: { _controller: WikiTagBundle:WikiTag:tagUpDown }
wikitag_remove_tag_from_list:
    pattern:  /wtrtfl
    defaults: { _controller: WikiTagBundle:WikiTag:removeTagFromList }
wikitag_modify_documenttag:
    pattern:  /wtmdt
    defaults: { _controller: WikiTagBundle:WikiTag:modifyDocumentTag }
wikitag_modify_tag_in_list:
    pattern:  /wtmtl
    defaults: { _controller: WikiTagBundle:WikiTag:modifyTag }
wikitag_relaunch_wp_search:
    pattern:  /wtrws
    defaults: { _controller: WikiTagBundle:WikiTag:relaunchWpSearch }
wikitag_reset_wp_info:
    pattern:  /wtrwi
    defaults: { _controller: WikiTagBundle:WikiTag:resetWpInfo }
wikitag_reorder_tag_document:
    pattern:  /wtrtd
    defaults: { _controller: WikiTagBundle:WikiTag:reorderTagDocument }
wikitag_add_tag:
    pattern:  /wtat
    defaults: { _controller: WikiTagBundle:WikiTag:addTag }
wikitag_remove_wp_link:
    pattern:  /wtrwl
    defaults: { _controller: WikiTagBundle:WikiTag:removeWpLink }
wikitag_update_tag_alias:
    pattern:  /wtupa
    defaults: { _controller: WikiTagBundle:WikiTag:updateTagAlias }
wikitag_update_tag_category:
    pattern:  /wtutc
    defaults: { _controller: WikiTagBundle:WikiTag:updateTagCategory }
    