##
# This file is part of the WikiTagBundle package.
#
# (c) IRI <http://www.iri.centrepompidou.fr/>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

parameters:
    wiki_tag.document_listener.class: IRI\Bundle\WikiTagBundle\Listener\DocumentListener
    wiki_tag.wiki_tag_document_listener.class: IRI\Bundle\WikiTagBundle\Listener\WikiTagDocumentListener
    wiki_tag.shema_utils.class: IRI\Bundle\WikiTagBundle\Utils\SchemaUtils
    wiki_tag.search_service_class: IRI\Bundle\WikiTagBundle\Services\SearchService
    wiki_tag.document_service_class: IRI\Bundle\WikiTagBundle\Services\DocumentService


services:

    wiki_tag.document_listener:
        class: %wiki_tag.document_listener.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    wiki_tag.wiki_tag_document_listener:
        class: %wiki_tag.wiki_tag_document_listener.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    wiki_tag.shema_utils:
        class: %wiki_tag.shema_utils.class%
        arguments: [@service_container]
        
    wiki_tag.search:
        class: %wiki_tag.search_service_class%
        arguments: [@service_container]

    wiki_tag.document:
        class: %wiki_tag.document_service_class%
        arguments: [@service_container]


#    wiki_tag.example:
#        class: %wiki_tag.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
