<?php
/*
 * This file is part of the WikiTagBundle package.
 *
 * (c) IRI <http://www.iri.centrepompidou.fr/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace IRI\Bundle\WikiTagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
    *  Find all Categories sorted by alphabetic order
    */
    public function findOrderedCategories()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT c.label FROM WikiTagBundle:Category c ORDER BY c.label ASC")
            ->getResult();
    }
    
}